version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tenis
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
    networks:
      - webnet
    entrypoint: ["/bin/sh", "-c",  "apache2-foreground"]

  db:
    image: mysql:8.0
    container_name: tenis_db
    ports:
      - "3308:3306"    
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tenis_db
      MYSQL_USER: tenis_user
      MYSQL_PASSWORD: tenis_password
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: tenis_phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: tenis_db
      PMA_PORT: 3306
      PMA_USER: tenis_user
      PMA_PASSWORD: tenis_password
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
